package dataoffice;

import net.proteanit.sql.DbUtils;

public class mainProgram extends javax.swing.JFrame {

    private final CommonVarriables customCodesObject = new CommonVarriables();
    private int xMousePosition;
    private int yMousePosition;

    public mainProgram() {
        initComponents();
        String Query = "SELECT " + customCodesObject.COLS_lISTING_users + " FROM " + customCodesObject.tablesToCreate[0];
        updateMainTable(Query);
    }

    private void updateMainTable(String DEFAULT_QUERY) {
        MainTable.setModel(DbUtils.resultSetToTableModel(customCodesObject.getResultSet(DEFAULT_QUERY)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SearchLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        TableScrollPane = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(new CommonVarriables().mainHeader);
        setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        setLocation(new java.awt.Point(10, 10));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 2, 40, 30));

        MinimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1193, 2, 40, 30));

        FrameDrag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CURRENT DATA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        jTextField1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 100, 23));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("jTextField2");
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 100, 23));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("jTextField3");
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 100, 23));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("jTextField4");
        jTextField4.setBorder(null);
        jTextField4.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 110, 100, 23));

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setText("jTextField5");
        jTextField5.setBorder(null);
        jTextField5.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, 100, 23));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("jTextField6");
        jTextField6.setBorder(null);
        jTextField6.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 170, 100, 23));

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setText("jTextField7");
        jTextField7.setBorder(null);
        jTextField7.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 200, 100, 23));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setText("jTextField8");
        jTextField8.setBorder(null);
        jTextField8.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 230, 100, 23));

        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jTextField9.setText("jTextField9");
        jTextField9.setBorder(null);
        jTextField9.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 260, 100, 23));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 210, 110, 290));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 70, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, 290));

        SearchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searcch.jpg"))); // NOI18N
        SearchLabel.setAlignmentY(0.0F);
        getContentPane().add(SearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 185, 40, 44));

        SearchTextField.setBorder(null);
        getContentPane().add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 185, 160, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 210, 160, -1));

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MainTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableScrollPane.setViewportView(MainTable);

        getContentPane().add(TableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 237, 730, 260));

        BackgroundImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackgroundImage.setForeground(new java.awt.Color(255, 255, 255));
        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back image 2.jpg"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        this.setState(mainProgram.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMousePosition, y - yMousePosition);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMousePosition = evt.getX();
        yMousePosition = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void mai(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JTable MainTable;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JScrollPane TableScrollPane;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
